package gr.publicsoft.springbootcrud.repository;

import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import gr.publicsoft.springbootcrud.model.Supplier;
import org.springframework.web.bind.annotation.CrossOrigin;

@CrossOrigin(origins = "http://localhost:9000")
@RepositoryRestResource
public interface  SupplierRepository extends JpaRepository<Supplier, Long>{

	 Optional<Supplier>  findByCompanyName(String companyName);
	 
	 @Query("SELECT s FROM Supplier s WHERE s.companyName = :companyName")
	 List<Supplier> findAllByCompanyName(@Param("companyName") String companyName);
	 
	 Optional<Supplier>  findByVatNumber(String Vatnumber);

	 /*
		Rest CRUD actions are automatically generated by Spring Framework
		through implementation of methods in JPA repository interface.
	*/
}
